
import React from 'react';
import Layout from '@/components/Layout';
import QRScanner from '@/components/QRScanner';
import { useToast } from "@/hooks/use-toast";
import { QrCode } from 'lucide-react';

const Scanner = () => {
  const { toast } = useToast();

  const handleScan = (data: string) => {
    try {
      const parsedData = JSON.parse(data);
      toast({
        title: "QR Scan Successful",
        description: `Verified ${parsedData.type}: ${parsedData.name}`,
      });
    } catch (error) {
      toast({
        title: "Invalid QR Code",
        description: "The scanned QR code is not valid.",
        variant: "destructive",
      });
      console.error("Error parsing scan data", error);
    }
  };

  return (
    <Layout>
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <h1 className="text-2xl font-bold text-access-primary flex items-center">
            <QrCode className="mr-2 h-6 w-6" />
            QR Scanner
          </h1>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <QRScanner onScan={handleScan} />
          </div>
          
          <div>
            <div className="bg-white p-6 rounded-lg shadow-sm border">
              <h2 className="text-xl font-semibold mb-4">Scanner Instructions</h2>
              <div className="space-y-4">
                <div className="border-l-4 border-access-primary pl-4 py-2">
                  <h3 className="font-medium">1. Position the ID Card</h3>
                  <p className="text-gray-600">Center the QR code within the scanning area</p>
                </div>
                <div className="border-l-4 border-access-primary pl-4 py-2">
                  <h3 className="font-medium">2. Scan the Code</h3>
                  <p className="text-gray-600">Hold steady until the scan is complete</p>
                </div>
                <div className="border-l-4 border-access-primary pl-4 py-2">
                  <h3 className="font-medium">3. Verify the Results</h3>
                  <p className="text-gray-600">Check status and expiration information</p>
                </div>
                <div className="border-l-4 border-access-primary pl-4 py-2">
                  <h3 className="font-medium">4. Take Appropriate Action</h3>
                  <p className="text-gray-600">Grant or deny access based on validation status</p>
                </div>
              </div>
              <div className="mt-6 p-4 bg-yellow-50 border border-yellow-100 rounded-md">
                <p className="text-sm text-yellow-800">
                  <strong>Note:</strong> For security purposes, the scanner will only recognize QR codes generated by this system.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Scanner;
